name: "Github App Token Generator"
description: "Generate a Github App Token to call Github APIs"
author: "Surat Mukker"
inputs:
  privateKey:
    description: "Private Key to generate the token for"
    required: true
  appId:
    description: "App Id of the App that private Key belongs to"
    required: true
  installId:
    description: "Github App InstallationId, the token is going to make calls to manage these resources"
    required: true
  duration:
    description: "Duration the token will be valid for in minutes, default value is 10 minutes"
    required: false
    default: 10
outputs:
  ghaToken:
    description: "Token valid for duration above"
    value: ${{ steps.fetch_gha_token.outputs.ghaToken }}
runs:
  using: "composite"
  steps:
    - id: fetch_gha_token
      run: |
        ghaToken=$($GITHUB_ACTION_PATH/gha_token_generator.sh)
        echo "ghaToken=$ghaToken" >> $GITHUB_OUTPUT
      env:
        PRIVATEKEY: ${{inputs.privateKey}}
        APPID: ${{inputs.appId}}
        INSTALLID: ${{inputs.installId}}
        DURATION: ${{inputs.duration}}
      shell: bash
